import { NextRequest, NextResponse } from 'next/server';
import { writeFile, mkdir, readFile } from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';
import { execSync } from 'child_process';

/**
 * POST /api/setup/install
 *
 * Performs the actual MoodleX installation:
 * 1. Writes the .env configuration file
 * 2. Updates Prisma schema for the selected database provider
 * 3. Runs database migrations (prisma db push)
 * 4. Applies table prefix via RENAME + VIEW (if configured)
 * 5. Creates the admin user and default data
 */
export async function POST(request: NextRequest) {
  try {
    const config = await request.json();
    const projectRoot = process.cwd();
    const steps: string[] = [];

    // Step 1: Build DATABASE_URL
    let databaseUrl = '';
    let prismaProvider = 'postgresql';

    switch (config.dbtype) {
      case 'postgresql':
        prismaProvider = 'postgresql';
        databaseUrl = `postgresql://${config.dbuser}:${encodeURIComponent(config.dbpass || '')}@${config.dbhost}:${config.dbport || '5432'}/${config.dbname}`;
        break;
      case 'mysql':
      case 'mariadb':
        prismaProvider = 'mysql';
        databaseUrl = `mysql://${config.dbuser}:${encodeURIComponent(config.dbpass || '')}@${config.dbhost}:${config.dbport || '3306'}/${config.dbname}`;
        break;
      case 'sqlite':
        prismaProvider = 'sqlite';
        databaseUrl = `file:./${config.dbname || 'moodle'}.db`;
        break;
      case 'sqlserver':
        prismaProvider = 'sqlserver';
        databaseUrl = `sqlserver://${config.dbhost}:${config.dbport || '1433'};database=${config.dbname};user=${config.dbuser};password=${config.dbpass};encrypt=true;trustServerCertificate=true`;
        break;
    }

    steps.push('✓ Database URL configured');

    // Step 2: Write .env file
    // Reuse the existing NEXTAUTH_SECRET so the running server doesn't need a restart.
    // Only generate a new one if none exists yet.
    const secret = process.env.NEXTAUTH_SECRET || generateSecret();
    const envContent = [
      '# MoodleX - Generated by Installation Wizard',
      `# Generated: ${new Date().toISOString()}`,
      '',
      '# Database Configuration',
      `DATABASE_PROVIDER="${prismaProvider}"`,
      `DATABASE_URL="${databaseUrl}"`,
      `DATABASE_PREFIX="${(config.dbprefix as string || '').trim()}"`,
      '',
      '# Authentication',
      `NEXTAUTH_URL="${config.wwwroot || 'http://localhost:3000'}"`,
      `NEXTAUTH_SECRET="${secret}"`,
      '',
      '# Site Configuration',
      `SITE_NAME="${config.sitename || 'MoodleX'}"`,
      `SITE_SHORTNAME="${config.siteshortname || 'moodlex'}"`,
      `SITE_URL="${config.wwwroot || 'http://localhost:3000'}"`,
      `DATA_ROOT="${config.dataroot || ''}"`,
      `DEFAULT_LANG="${config.lang || 'en'}"`,
      `DEFAULT_TIMEZONE="${config.timezone || 'UTC'}"`,
      '',
      '# Installed flag',
      'MOODLE_INSTALLED="true"',
    ].join('\n');

    await writeFile(path.join(projectRoot, '.env'), envContent, 'utf-8');
    steps.push('✓ Environment configuration written');

    // Clear the cached PrismaClient singleton so subsequent requests
    // (e.g. login) use the new DATABASE_URL from the updated .env
    const g = globalThis as unknown as { prisma?: { $disconnect?: () => Promise<void> } };
    if (g.prisma) {
      try { await g.prisma.$disconnect?.(); } catch { /* ignore */ }
      delete g.prisma;
    }

    // Step 3: Create data directory structure
    const dataRoot = config.dataroot;
    if (dataRoot) {
      const dirs = ['cache', 'lang', 'temp', 'sessions', 'files', 'backup'];
      for (const dir of dirs) {
        const dirPath = path.join(dataRoot, dir);
        if (!existsSync(dirPath)) {
          try {
            await mkdir(dirPath, { recursive: true });
          } catch {
            // May fail for system paths
          }
        }
      }
      steps.push('✓ Data directory structure created');
    }

    // Step 4: Update Prisma schema provider (NO @@map — prefix is handled via SQL views)
    const schemaPath = path.join(projectRoot, 'prisma', 'schema.prisma');
    const schemaTemplatePath = path.join(projectRoot, 'prisma', 'schema.prisma.template');
    if (existsSync(schemaPath)) {
      // Save a backup of the original schema as template (for future reinstalls)
      if (!existsSync(schemaTemplatePath)) {
        const currentSchema = await readFile(schemaPath, 'utf-8');
        await writeFile(schemaTemplatePath, currentSchema, 'utf-8');
      }
      // Always read from template if available to get clean @db.Text annotations
      const sourceSchemaPath = existsSync(schemaTemplatePath) ? schemaTemplatePath : schemaPath;
      let schema = await readFile(sourceSchemaPath, 'utf-8');
      schema = schema.replace(
        /provider\s*=\s*"(postgresql|mysql|sqlite|sqlserver)"/,
        `provider = "${prismaProvider}"`
      );
      // SQLite doesn't support @db.Text - remove those annotations
      if (prismaProvider === 'sqlite') {
        schema = schema.replace(/\s*@db\.Text/g, '');
      }
      // Strip any @@map directives that may have leaked from a previous install
      schema = schema.replace(/\s*@@map\("[^"]*"\)\n?/g, '\n');
      await writeFile(schemaPath, schema, 'utf-8');
      steps.push(`✓ Prisma schema updated for ${prismaProvider}`);
    }

    // Step 5: Generate Prisma client and push schema to database
    try {
      execSync('npx prisma generate', {
        cwd: projectRoot,
        env: { ...process.env, DATABASE_URL: databaseUrl },
        stdio: 'pipe',
        timeout: 60000,
      });
      steps.push('✓ Prisma client generated');

      execSync('npx prisma db push --accept-data-loss', {
        cwd: projectRoot,
        env: { ...process.env, DATABASE_URL: databaseUrl },
        stdio: 'pipe',
        timeout: 60000,
      });
      steps.push('✓ Database tables created');
    } catch (err: unknown) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      const stderr = (err as { stderr?: Buffer })?.stderr?.toString() || '';
      return NextResponse.json({
        ok: false,
        message: `Database setup failed: ${stderr || errorMsg}`,
        steps,
      }, { status: 500 });
    }

    // Step 6: Apply table prefix via RENAME + VIEW
    // This approach keeps the Prisma schema clean (no @@map) so the running
    // PrismaClient doesn't need regeneration. Tables are renamed, and views
    // with the original names allow Prisma to query transparently.
    const dbprefix = (config.dbprefix as string || '').trim();
    if (dbprefix && prismaProvider !== 'sqlite') {
      try {
        const schema = await readFile(schemaPath, 'utf-8');
        const modelNames = extractModelNames(schema);
        const prefixScript = buildPrefixScript(modelNames, dbprefix, prismaProvider, databaseUrl);
        const prefixPath = path.join(projectRoot, 'prisma', '_prefix_tables.mjs');
        await writeFile(prefixPath, prefixScript, 'utf-8');

        const prefixOutput = execSync(`node "${prefixPath}"`, {
          cwd: projectRoot,
          env: { ...process.env, DATABASE_URL: databaseUrl },
          stdio: 'pipe',
          timeout: 30000,
        }).toString();

        const prefixSteps = prefixOutput.trim().split('\n').filter(Boolean);
        steps.push(...prefixSteps);

        // Clean up
        try {
          const { unlink } = await import('fs/promises');
          await unlink(prefixPath);
        } catch { /* ignore */ }
      } catch (prefixError: unknown) {
        const errMsg = prefixError instanceof Error ? prefixError.message : String(prefixError);
        const stderr = (prefixError as { stderr?: Buffer })?.stderr?.toString() || '';
        return NextResponse.json({
          ok: false,
          message: `Table prefix failed: ${stderr || errMsg}`,
          steps,
        }, { status: 500 });
      }
    }

    // Step 7: Seed admin user and default data via external script
    // Must run in a separate process because the in-memory PrismaClient
    // is cached from before we regenerated the schema
    try {
      const seedScript = buildSeedScript(config, databaseUrl);
      const seedPath = path.join(projectRoot, 'prisma', '_seed_install.mjs');
      await writeFile(seedPath, seedScript, 'utf-8');

      const seedOutput = execSync(`node "${seedPath}"`, {
        cwd: projectRoot,
        env: { ...process.env, DATABASE_URL: databaseUrl },
        stdio: 'pipe',
        timeout: 60000,
      }).toString();

      // Parse seed output for step messages
      const seedSteps = seedOutput.trim().split('\n').filter(Boolean);
      steps.push(...seedSteps);

      // Clean up seed script
      try {
        const { unlink } = await import('fs/promises');
        await unlink(seedPath);
      } catch { /* ignore */ }
    } catch (seedError: unknown) {
      const errMsg = seedError instanceof Error ? seedError.message : String(seedError);
      const stderr = (seedError as { stderr?: Buffer })?.stderr?.toString() || '';
      return NextResponse.json({
        ok: false,
        message: `Data seeding failed: ${stderr || errMsg}`,
        steps,
      }, { status: 500 });
    }

    steps.push('✓ Installation completed successfully!');

    return NextResponse.json({
      ok: true,
      message: 'Installation completed successfully!',
      steps,
      details: {
        prismaProvider,
        databaseUrl: databaseUrl.replace(/:[^:@]*@/, ':****@'),
        adminUser: config.adminuser,
        siteName: config.sitename,
      },
    });
  } catch (error) {
    return NextResponse.json(
      {
        ok: false,
        message: error instanceof Error ? error.message : 'Installation failed.',
      },
      { status: 500 }
    );
  }
}

/** Extract all model names from a Prisma schema */
function extractModelNames(schema: string): string[] {
  const matches = schema.matchAll(/model\s+(\w+)\s*\{/g);
  return [...matches].map((m) => m[1]);
}

/**
 * Builds an external Node script that renames database tables and creates
 * views with the original names. This allows the Prisma client (which has
 * no @@map directives) to transparently query the prefixed tables via views.
 *
 * MySQL updatable views on single tables support INSERT, UPDATE, DELETE.
 * PostgreSQL auto-updatable views likewise support full DML.
 * SQL Server supports INSERT/UPDATE/DELETE on single-table views.
 */
function buildPrefixScript(
  modelNames: string[],
  prefix: string,
  provider: string,
  databaseUrl: string
): string {
  // Build the script as an array of lines to avoid backtick/template-literal issues
  const lines: string[] = [
    "import { PrismaClient } from '@prisma/client';",
    "",
    "const prisma = new PrismaClient({",
    "  datasources: { db: { url: " + JSON.stringify(databaseUrl) + " } },",
    "});",
    "",
    "const models = " + JSON.stringify(modelNames) + ";",
    "const prefix = " + JSON.stringify(prefix) + ";",
    "const provider = " + JSON.stringify(provider) + ";",
    "// Backtick character for MySQL quoting",
    "const q = String.fromCharCode(96);",
    "",
    "async function applyPrefix() {",
    "  if (provider === 'mysql') {",
    "    const renames = models.map(m => q + m + q + ' TO ' + q + prefix + m + q).join(', ');",
    "    await prisma.$executeRawUnsafe('RENAME TABLE ' + renames);",
    "    console.log('\\u2713 Tables renamed with prefix \"' + prefix + '\"');",
    "    for (const m of models) {",
    "      await prisma.$executeRawUnsafe('CREATE VIEW ' + q + m + q + ' AS SELECT * FROM ' + q + prefix + m + q);",
    "    }",
    "    console.log('\\u2713 Database views created for transparent access');",
    "  } else if (provider === 'postgresql') {",
    '    for (const m of models) {',
    '      await prisma.$executeRawUnsafe(\'ALTER TABLE "\' + m + \'" RENAME TO "\' + prefix + m + \'"\');',
    "    }",
    "    console.log('\\u2713 Tables renamed with prefix \"' + prefix + '\"');",
    '    for (const m of models) {',
    '      await prisma.$executeRawUnsafe(\'CREATE VIEW "\' + m + \'" AS SELECT * FROM "\' + prefix + m + \'"\');',
    "    }",
    "    console.log('\\u2713 Database views created for transparent access');",
    "  } else if (provider === 'sqlserver') {",
    '    for (const m of models) {',
    "      await prisma.$executeRawUnsafe(\"EXEC sp_rename '\" + m + \"', '\" + prefix + m + \"'\");",
    "    }",
    "    console.log('\\u2713 Tables renamed with prefix \"' + prefix + '\"');",
    '    for (const m of models) {',
    "      await prisma.$executeRawUnsafe('CREATE VIEW [' + m + '] AS SELECT * FROM [' + prefix + m + ']');",
    "    }",
    "    console.log('\\u2713 Database views created for transparent access');",
    "  }",
    "  await prisma.$disconnect();",
    "}",
    "",
    "applyPrefix().catch(async (e) => {",
    "  console.error(e);",
    "  await prisma.$disconnect();",
    "  process.exit(1);",
    "});",
  ];

  return lines.join('\n');
}

function buildSeedScript(config: Record<string, string | boolean>, databaseUrl: string): string {
  const adminuser = config.adminuser || 'admin';
  const adminemail = config.adminemail || 'admin@localhost';
  const adminfirstname = config.adminfirstname || 'Admin';
  const adminlastname = config.adminlastname || 'User';
  const adminpass = config.adminpass as string;
  const sitename = config.sitename || 'MoodleX';
  const siteshortname = config.siteshortname || 'moodlex';
  const lang = config.lang || 'en';
  const timezone = config.timezone || 'UTC';
  const selfregistration = config.selfregistration ? 'true' : 'false';

  return `
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient({
  datasources: { db: { url: ${JSON.stringify(databaseUrl)} } },
});

async function seed() {
  const hashedPassword = await bcrypt.hash(${JSON.stringify(adminpass)}, 12);

  const adminUser = await prisma.user.create({
    data: {
      username: ${JSON.stringify(adminuser)},
      email: ${JSON.stringify(adminemail)},
      password: hashedPassword,
      firstname: ${JSON.stringify(adminfirstname)},
      lastname: ${JSON.stringify(adminlastname)},
      role: 'admin',
      confirmed: true,
      suspended: false,
      deleted: false,
      city: '',
      country: '',
      timezone: ${JSON.stringify(timezone)},
      lang: ${JSON.stringify(lang)},
      description: '',
    },
  });
  console.log('✓ Admin user "' + ${JSON.stringify(adminuser)} + '" created');

  const defaultCategory = await prisma.courseCategory.create({
    data: {
      name: 'Miscellaneous',
      description: 'Default course category',
      sortorder: 1,
      visible: true,
      depth: 1,
      path: '/1',
    },
  });
  console.log('✓ Default course category created');

  const sampleCourse = await prisma.course.create({
    data: {
      fullname: 'Introduction to MoodleX',
      shortname: 'MOODLEX101',
      summary: 'Welcome to your new MoodleX site! This is a sample course to help you get started.',
      categoryId: defaultCategory.id,
      format: 'topics',
      startdate: new Date(),
      visible: true,
      numsections: 4,
    },
  });
  console.log('✓ Sample course created');

  await prisma.enrollment.create({
    data: {
      userId: adminUser.id,
      courseId: sampleCourse.id,
      role: 'editingteacher',
      status: 'active',
      enrolMethod: 'manual',
    },
  });
  console.log('✓ Admin enrolled in sample course');

  const sectionNames = ['General', 'Getting Started', 'Course Features', 'Next Steps'];
  for (let i = 0; i < sectionNames.length; i++) {
    await prisma.courseSection.create({
      data: {
        courseId: sampleCourse.id,
        name: sectionNames[i],
        summary: '',
        section: i,
        visible: true,
      },
    });
  }
  console.log('✓ Course sections created');

  const configs = [
    { name: 'sitename', value: ${JSON.stringify(sitename)} },
    { name: 'shortname', value: ${JSON.stringify(siteshortname)} },
    { name: 'lang', value: ${JSON.stringify(lang)} },
    { name: 'timezone', value: ${JSON.stringify(timezone)} },
    { name: 'selfregistration', value: ${JSON.stringify(selfregistration)} },
  ];
  for (const c of configs) {
    await prisma.siteConfig.create({ data: c });
  }
  console.log('✓ Site configuration saved');

  await prisma.$disconnect();
}

seed().catch(async (e) => {
  console.error(e);
  await prisma.$disconnect();
  process.exit(1);
});
`;
}

function generateSecret(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < 64; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}
